WIP - Newsletter sign-up form
kailanyy/front-end-mentor pull request #1
Opened 2023-06-30 15:49 UTC by kailanyy

2023-07-27 15:42 UTC, kailanyy commented on src/App.vue
> +    <!-- <router-link :to="{name: 'home'}">home</router-link>
Verificar se essas linhas são necessárias

2023-09-02 16:36 UTC, ChrystianFerreira commented on src/App.vue
> +    <!-- <router-link :to="{name: 'home'}">home</router-link>
Pode remover! Não tenha medo de apagar código, qualquer coisa é só olhar os commits e encontrar o que foi removido.

2023-09-02 16:37 UTC, ChrystianFerreira commented on src/components/Chat.vue
> +  <div class="flex flex-col h-full w-full bg-white dark:bg-gray-900 px-4 py-6">
O que esse `dark:bg-gray-900` aqui faz? Se não faz nada, pode ser removido!

2023-09-02 16:38 UTC, ChrystianFerreira commented on src/components/Chat.vue
Esse componente deve ser removido!

2023-09-02 16:46 UTC, ChrystianFerreira commented on src/components/NewsletterSignUpForm/NewsletterSignUpForm.vue
> +            <img class="mr-2" src="@/assets/NewsletterSignUpForm/images/icon-list.svg" alt=""> {{ item.message }}
Seria bom colocar o texto do alt aqui, mesmo que seja algo como "Item da lista de mensagens que serão recebidas"

2023-09-02 16:46 UTC, ChrystianFerreira commented on src/components/NewsletterSignUpForm/NewsletterSignUpForm.vue
> +            <img class="mr-2" src="@/assets/NewsletterSignUpForm/images/icon-list.svg" alt=""> {{ item.message }}
Em inglês :p

2023-09-02 16:53 UTC, ChrystianFerreira commented on src/components/NewsletterSignUpForm/NewsletterSignUpForm.vue
> +            :class="[v$.email.$errors.length > 0 ? 'bg-[#ff44442a] border-newsletter-dark-slate-grey placeholder-newsletter-dark-slate-grey' : 'border-newsletter-grey placeholder-newsletter-grey']">
Esse estilo tá dentro de uma lista, mas não precisa estar. Pode ser mudado para:
`:class="v$.email.$errors.length > 0 ? 'bg-[#ff44442a] border-newsletter-dark-slate-grey placeholder-newsletter-dark-slate-grey' : 'border-newsletter-grey placeholder-newsletter-grey'"`

2023-09-02 16:57 UTC, ChrystianFerreira commented on src/components/NewsletterSignUpForm/NewsletterSignUpForm.vue
> +        <!-- <img class="block md:hidden rounded-2xl" src="@/assets/NewsletterSignUpForm/images/illustration-sign-up-mobile.svg"> -->
Remover comentário

2023-09-02 16:57 UTC, ChrystianFerreira commented on src/components/NewsletterSignUpForm/NewsletterSignUpForm.vue
> +    <NewsletterSuccess :email="state.email" @dismiss="subscribed = false" />
Poderia colocar o v-else diretamente no componente NewsletterSuccess

2023-09-02 17:03 UTC, ChrystianFerreira commented on src/components/NewsletterSignUpForm/NewsletterSignUpForm.vue
> +            /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/.test(value)
Nem todo mundo sabe ler regex e, mesmo que saiba, é algo que toma certo tempo. Poderias colocar a verificação do regex dentro de uma constante logo antes da computed 'rules' que contivesse o regex, mas com um nome que deixasse mais fácil de entender do que se trata, aí ficaria parecido com isso: constanteQueGuardaORegex.test(value)

2023-09-02 17:03 UTC, ChrystianFerreira commented on src/components/NewsletterSignUpForm/NewsletterSignUpForm.vue
> +    const items = ([
Acho que dá pra remover o ( ) que está ao redor da lista.

2023-09-02 17:03 UTC, ChrystianFerreira commented on src/components/NewsletterSignUpForm/NewsletterSignUpForm.vue
> +      const invalid = await v$.value.$validate().then(valid /* true ou false */ => valid === false)
Dá pra remover esse comentário true ou false aqui

2023-09-02 17:07 UTC, ChrystianFerreira commented on src/views/About.vue
> +import NewsletterSuccess from '../components/NewsletterSignUpForm/NewsletterSuccess.vue'
Vê se consegue alterar esse import para usar o @ no começo.

2023-09-02 17:07 UTC, ChrystianFerreira commented on src/views/Home.vue
> +import NewsletterSignUpForm from "../components/NewsletterSignUpForm/NewsletterSignUpForm.vue"
Vê se consegue alterar esse import para usar o @ no começo.

2023-09-02 17:07 UTC, ChrystianFerreira requested changes
Apenas algumas alterações simples :)

2023-09-15 15:34 UTC, kailanyy commented
Alterações foram feitas no PR da branch initial-layout https://github.com/kailanyy/front-end-mentor/pull/2/commits/2bc5fd5209e20fdcc74ad97bd1688fb7e246b8ba

2023-09-15 15:35 UTC, ChrystianFerreira approved these changes

2023-09-15 15:35 UTC, merged